### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fstrazzante** [oanda/v20-javascript#2]
Hello,
where could I find the javascript documentation? Because at the link indicated in this readme I can see only curl examples and I can't find javascript documentation/examples.
Thanks

**Comment by mrchrisok** [comment]
Go to http://developer.oanda.com/rest-live-v20/introduction/ to see OANDA's extensive documentation for the V20 api.

I've written a TypeScript d.ts file for it. It's in my repo for a project that consumes the V20 api.  Link to the d.ts is: https://github.com/mrchrisok/argomarketminer/blob/development/typings/%40oanda.v20.d.ts.

The d.ts is offered "as-is".  It's accurate as of today. Will get around to dropping it into a pull request one of these days.
/oco

**Comment by fstrazzante** [comment]
Ok perfect, Thank you 👍
